version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: rspec_explain_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rspec_explain_test
      MYSQL_USER: rspec_user
      MYSQL_PASSWORD: rspec_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: